// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTd4YGdz0XrL_5TELnzo7Mqdj5DC_wir0',
    appId: '1:860400078470:web:29ecc328eef922633a0b07',
    messagingSenderId: '860400078470',
    projectId: 'jom-tapau-mobile',
    authDomain: 'jom-tapau-mobile.firebaseapp.com',
    storageBucket: 'jom-tapau-mobile.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMM_w6WwecA_HjHO5J--NYhkwLAi5izpI',
    appId: '1:860400078470:android:487afeba3ac1b55a3a0b07',
    messagingSenderId: '860400078470',
    projectId: 'jom-tapau-mobile',
    storageBucket: 'jom-tapau-mobile.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmClCBaieUW0iAMdJAxjJHwfEZyyG-Gak',
    appId: '1:860400078470:ios:f66373b5d355a4fc3a0b07',
    messagingSenderId: '860400078470',
    projectId: 'jom-tapau-mobile',
    storageBucket: 'jom-tapau-mobile.appspot.com',
    iosClientId: '860400078470-q3i8fa0uqam0aopv3e5j6bpson38ebis.apps.googleusercontent.com',
    iosBundleId: 'com.example.jomTapauMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmClCBaieUW0iAMdJAxjJHwfEZyyG-Gak',
    appId: '1:860400078470:ios:f66373b5d355a4fc3a0b07',
    messagingSenderId: '860400078470',
    projectId: 'jom-tapau-mobile',
    storageBucket: 'jom-tapau-mobile.appspot.com',
    iosClientId: '860400078470-q3i8fa0uqam0aopv3e5j6bpson38ebis.apps.googleusercontent.com',
    iosBundleId: 'com.example.jomTapauMobile',
  );
}
